### PR TITLE
Redesign and introducing Mottled-Library

### PR DESCRIPTION
**Pull request by wirednkod**
This PR has two reasons of existence:

a) redesign the Metadata Portal based on given Figma file (can be found [here](https://www.figma.com/file/eOnz3xbzObTG8hQlIRs6jg/Metadata-Portal?node-id=0%3A1)) by @dnlklmn 
b) introduce the very first (buggy) draft version of [Mottled-library](https://github.com/paritytech/mottled-library) (reusable components and recipes created for substrate chains)

The outcome can be found in the screenshots below:

image
image
 
NOTE: There are some fixings still needed for mobile version but I would like to address them in a different PR once this is approved and merged

### CODE REVIEW

**Comment by prybalko** [comment]
Thanks @wirednkod! Very nice design. A couple of questions though:
1. `Developed by Parity` and `Terms of Service` links are overlaid on the content
Screenshot 2022-04-12 at 11 56 51 Is it something you were going to fix in the next PR?

2. Seems like chain colors are taken from the `motted-library`, but it has info only about 4 chains. That's quite limmiting, because metadata portal can be used for any substrate parachain. My approach was to specify colors in the config file https://github.com/paritytech/metadata-portal/blob/master/config.toml#L12. Do you mind adding `primaryColor` and `secondaryColor` in there?
3. > NOTE: There are some fixings still needed for mobile version but I would like to address them in a different PR once this is approved and merged

Is there a reason not to incluse fixes in this PR? Once it's merged, it's going to be automatically deployed to https://metadata.parity.io/

**Comment by wirednkod** [comment]
> 1. `Developed by Parity` and `Terms of Service` links are overlaid on the content

This is a 🤦🏽 moment. Thank you for that

> 2. Seems like chain colors are taken from the `motted-library`, but it has info only about 4 chains. That's quite limmiting, because metadata portal can be used for any substrate parachain. My approach was to specify colors in the config file https://github.com/paritytech/metadata-portal/blob/master/config.toml#L12. Do you mind adding `primaryColor` and `secondaryColor` in there?

I can do that - the idea though is to have things like colors etc in 1 place (reason why the mottled-library was created in the first place). More chains will be added soon (next step is actually to pass all chains from polkadotjs).
What do you think? Should I update toml or keep it in the library for the metadata-portal? Any option would work for me... 

> 3. > NOTE: There are some fixings still needed for mobile version but I would like to address them in a different PR once this is approved and merged
> 
> Is there a reason not to incluse fixes in this PR? Once it's merged, it's going to be automatically deployed to https://metadata.parity.io/

Did not know that it is automatically deployed - will address on this PR then.

Thank you

**Comment by prybalko** [comment]
> I can do that - the idea though is to have things like colors etc in 1 place (reason why the mottled-library was created in the first place). More chains will be added soon (next step is actually to pass all chains from polkadotjs).

Ok, perfect, let's use that 👍

**Comment by wirednkod** [comment]
Mobile Version:
image

**Review by prybalko — APPROVED** [review]
Looks good 👍

**Pull request merged**
